const IndianCityData = [
  { code: "DEL", city: "Delhi" },
  { code: "MUM", city: "Mumbai" },
  { code: "BLR", city: "Bengaluru" },
  { code: "CHE", city: "Chennai" },
  { code: "KOL", city: "Kolkata" },
  { code: "HYD", city: "Hyderabad" },
  { code: "PUN", city: "Pune" },
  { code: "AHM", city: "Ahmedabad" },
  { code: "SUR", city: "Surat" },
  { code: "JAI", city: "Jaipur" },
  { code: "KAN", city: "Kanpur" },
  { code: "LUC", city: "Lucknow" },
  { code: "NAG", city: "Nagpur" },
  { code: "IND", city: "Indore" },
  { code: "PAT", city: "Patna" },
  { code: "BHO", city: "Bhopal" },
  { code: "LUD", city: "Ludhiana" },
  { code: "VAR", city: "Varanasi" },
  { code: "AGR", city: "Agra" },
  { code: "NVA", city: "Navi Mumbai" },
  { code: "VIZ", city: "Visakhapatnam" },
  { code: "COI", city: "Coimbatore" },
  { code: "MYS", city: "Mysuru" },
  { code: "TRI", city: "Tiruchirappalli" },
  { code: "MNG", city: "Mangalore" },
  { code: "CHD", city: "Chandigarh" },
  { code: "GUR", city: "Gurgaon" },
  { code: "NOI", city: "Noida" },
  { code: "FAR", city: "Faridabad" },
  { code: "GHA", city: "Ghaziabad" },
  { code: "JOD", city: "Jodhpur" },
  { code: "UDA", city: "Udaipur" },
  { code: "ALL", city: "Allahabad" },
  { code: "RAN", city: "Ranchi" },
  { code: "GWA", city: "Gwalior" },
  { code: "JAB", city: "Jabalpur" },
  { code: "CUT", city: "Cuttack" },
  { code: "BBS", city: "Bhubaneswar" },
  { code: "RAI", city: "Raipur" },
  { code: "VAD", city: "Vadodara" },
  { code: "MAD", city: "Madurai" },
  { code: "SAH", city: "Saharanpur" },
  { code: "AMA", city: "Amritsar" },
  { code: "JAM", city: "Jamnagar" },
  { code: "DAV", city: "Davanagere" },
  { code: "KOC", city: "Kochi" },
  { code: "TRV", city: "Thiruvananthapuram" },
  { code: "GWA", city: "Guwahati" },
  { code: "SIL", city: "Silchar" },
  { code: "DIM", city: "Dimapur" }
];

export default IndianCityData;