const indianAirports = [
  { code: "DEL", name: "Indira Gandhi International Airport", city: "Delhi" },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai" },
  { code: "BLR", name: "Kempegowda International Airport", city: "Bengaluru" },
  { code: "MAA", name: "Chennai International Airport", city: "Chennai" },
  { code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad" },
  { code: "CCU", name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata" },
  { code: "COK", name: "Cochin International Airport", city: "Kochi" },
  { code: "AMD", name: "Sardar Vallabhbhai Patel International Airport", city: "Ahmedabad" },
  { code: "GOI", name: "Dabolim Airport", city: "Goa" },
  { code: "PNQ", name: "Pune International Airport", city: "Pune" },
  { code: "GAU", name: "Lokpriya Gopinath Bordoloi International Airport", city: "Guwahati" },
  { code: "TRV", name: "Trivandrum International Airport", city: "Thiruvananthapuram" },
  { code: "IXC", name: "Chandigarh International Airport", city: "Chandigarh" },
  { code: "LKO", name: "Chaudhary Charan Singh International Airport", city: "Lucknow" },
  { code: "BBI", name: "Biju Patnaik International Airport", city: "Bhubaneswar" },
  { code: "JAI", name: "Jaipur International Airport", city: "Jaipur" },
  { code: "VNS", name: "Lal Bahadur Shastri International Airport", city: "Varanasi" },
  { code: "IXB", name: "Bagdogra International Airport", city: "Siliguri" },
  { code: "SXR", name: "Sheikh ul-Alam International Airport", city: "Srinagar" },
  { code: "IXJ", name: "Jammu Airport", city: "Jammu" },
  { code: "IXM", name: "Madurai Airport", city: "Madurai" },
  { code: "IXE", name: "Mangalore International Airport", city: "Mangalore" },
  { code: "IXZ", name: "Veer Savarkar International Airport", city: "Port Blair" },
  { code: "IXR", name: "Birsa Munda Airport", city: "Ranchi" },
  { code: "PAT", name: "Jay Prakash Narayan International Airport", city: "Patna" },
  { code: "NAG", name: "Dr. Babasaheb Ambedkar International Airport", city: "Nagpur" },
  { code: "DED", name: "Jolly Grant Airport", city: "Dehradun" },
  { code: "RAJ", name: "Rajkot Airport", city: "Rajkot" },
  { code: "IXA", name: "Maharaja Bir Bikram Airport", city: "Agartala" },
  { code: "DIB", name: "Dibrugarh Airport", city: "Dibrugarh" },
  { code: "STV", name: "Surat Airport", city: "Surat" },
  { code: "TIR", name: "Tirupati Airport", city: "Tirupati" },
  { code: "IXL", name: "Kushok Bakula Rimpochee Airport", city: "Leh" },
  { code: "BDQ", name: "Vadodara Airport", city: "Vadodara" },
  { code: "IXD", name: "Prayagraj Airport", city: "Prayagraj" },
  { code: "VGA", name: "Vijayawada Airport", city: "Vijayawada" },
  { code: "HJR", name: "Khajuraho Airport", city: "Khajuraho" },
  { code: "RPR", name: "Swami Vivekananda Airport", city: "Raipur" },
  { code: "IXI", name: "Lilabari Airport", city: "North Lakhimpur" },
  { code: "IXW", name: "Sonari Airport", city: "Jamshedpur" },
  { code: "IXK", name: "Keshod Airport", city: "Keshod" },
  { code: "IXG", name: "Belgaum Airport", city: "Belagavi" },
  { code: "IXU", name: "Aurangabad Airport", city: "Aurangabad" },
  { code: "MYQ", name: "Mysore Airport", city: "Mysuru" },
  { code: "JDH", name: "Jodhpur Airport", city: "Jodhpur" },
  { code: "BDH", name: "Bhuj Airport", city: "Bhuj" },
  { code: "IMF", name: "Imphal International Airport", city: "Imphal" },
  { code: "IXS", name: "Silchar Airport", city: "Silchar" },
  { code: "ATQ", name: "Sri Guru Ram Dass Jee International Airport", city: "Amritsar" }
];

export default indianAirports;